# Generated by Django 2.1.1 on 2018-11-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageheader',
            name='logo',
            field=models.ImageField(blank=True, default='storey/header-default.jpg', upload_to='storey'),
        ),
        migrations.AlterField(
            model_name='homepageproductdemo',
            name='picture_1',
            field=models.ImageField(blank=True, default='storey/product_demo_1_default.jpg', upload_to='storey'),
        ),
        migrations.AlterField(
            model_name='homepageproductdemo',
            name='picture_2',
            field=models.ImageField(blank=True, default='storey/product_demo_2_default.jpg', upload_to='storey'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='store',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
