# Generated by Django 2.1.1 on 2018-11-28 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0005_auto_20181128_0117'),
        ('storey', '0002_auto_20181128_0019'),
    ]

    operations = [
    ]
