# Generated by Django 2.1.1 on 2018-11-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0007_auto_20181128_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageheader',
            name='text',
            field=models.CharField(default='Welcome to my website', max_length=40),
        ),
    ]
