# Generated by Django 2.1.1 on 2018-11-28 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0008_auto_20181128_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagefooter',
            name='isVisible',
        ),
        migrations.RemoveField(
            model_name='homepageheader',
            name='isVisible',
        ),
        migrations.RemoveField(
            model_name='homepagenavbar',
            name='isVisible',
        ),
    ]
