# Generated by Django 2.1.1 on 2018-11-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0009_auto_20181128_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagefooter',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='homepagefooter',
            name='link_1_content',
        ),
        migrations.RemoveField(
            model_name='homepagefooter',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='homepagefooter',
            name='link_2_content',
        ),
        migrations.RemoveField(
            model_name='homepagefooter',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='homepagefooter',
            name='promotion_content',
        ),
        migrations.AddField(
            model_name='homepagefooter',
            name='Company',
            field=models.CharField(default='Ali zz Company', max_length=40),
        ),
        migrations.AddField(
            model_name='homepagefooter',
            name='Shopname',
            field=models.CharField(default='My Shop', max_length=40),
        ),
    ]
