# Generated by Django 2.1.1 on 2018-11-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0010_auto_20181128_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefooter',
            name='Company',
            field=models.CharField(default='Company Name', max_length=40),
        ),
        migrations.AlterField(
            model_name='homepagefooter',
            name='Shopname',
            field=models.CharField(default='Shop Name', max_length=40),
        ),
    ]
