# Generated by Django 2.2.dev20180903084355 on 2018-11-19 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.CharField(default='', max_length=400)),
                ('category', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Kids', 'Kids')], default='man', max_length=40)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('picture', models.ImageField(blank=True, default='', upload_to='storey')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('storename', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my_shop', max_length=40)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storey.Retailer')),
            ],
        ),
        migrations.CreateModel(
            name='Shopwebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='my_shop', max_length=40)),
                ('theme', models.IntegerField(default=1)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storey.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageNavbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVisible', models.BooleanField(default=True)),
                ('text', models.CharField(default='This is a homepage navbar', max_length=40)),
                ('logo', models.ImageField(blank=True, default='storey/default-user-image.png', upload_to='storey')),
                ('logo_height', models.IntegerField(default=40)),
                ('logo_width', models.IntegerField(default=40)),
                ('homepage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storey.Homepage')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVisible', models.BooleanField(default=True)),
                ('text', models.CharField(default='This is a homepage header', max_length=40)),
                ('logo', models.ImageField(blank=True, default='storey/default-user-image.png', upload_to='storey')),
                ('homepage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storey.Homepage')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVisible', models.BooleanField(default=True)),
                ('link_1', models.CharField(default='', max_length=40)),
                ('link_1_content', models.CharField(default='', max_length=40)),
                ('link_2', models.CharField(default='', max_length=40)),
                ('link_2_content', models.CharField(default='', max_length=40)),
                ('promotion', models.CharField(default='', max_length=40)),
                ('promotion_content', models.CharField(default='', max_length=40)),
                ('homepage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storey.Homepage')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storey.Shopwebsite'),
        ),
        migrations.CreateModel(
            name='CollectionpageAllignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=4)),
                ('col', models.IntegerField(default=4)),
                ('sorting', models.BooleanField(default=True)),
                ('filtering', models.BooleanField(default=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storey.Shopwebsite')),
            ],
        ),
    ]
