# Generated by Django 2.1.1 on 2018-11-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0001_initial'),
    ]

    operations = [
    ]
