# Generated by Django 2.1.1 on 2018-11-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0002_auto_20181118_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionpageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenting', models.BooleanField(default=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storey.Shopwebsite')),
            ],
        ),
    ]
