# Generated by Django 2.2.dev20180903084355 on 2018-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0004_auto_20181119_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpagedetail',
            name='commenting',
            field=models.BooleanField(default=True),
        ),
    ]
