# Generated by Django 2.1.3 on 2018-11-19 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storey', '0005_auto_20181119_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(default='Category 1', max_length=40)),
                ('description_1', models.CharField(default='describe your category', max_length=300)),
                ('picture_1', models.ImageField(blank=True, default='', upload_to='storery')),
                ('name_2', models.CharField(default='Category 2', max_length=40)),
                ('description_2', models.CharField(default='describe your category', max_length=300)),
                ('picture_2', models.ImageField(blank=True, default='', upload_to='storery')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
