# Generated by Django 2.2.dev20180903084355 on 2018-11-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0006_productdemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpageallignment',
            name='col',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='collectionpageallignment',
            name='row',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='homepageheader',
            name='text',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='homepagenavbar',
            name='text',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='productdemo',
            name='description_1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='productdemo',
            name='description_2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='productdemo',
            name='name_1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='productdemo',
            name='name_2',
            field=models.CharField(default='', max_length=40),
        ),
    ]
