# Generated by Django 2.1.1 on 2018-11-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVisible', models.BooleanField()),
                ('link_1', models.CharField(max_length=40)),
                ('link_1_content', models.CharField(max_length=40)),
                ('link_2', models.CharField(max_length=40)),
                ('link_2_content', models.CharField(max_length=40)),
                ('promotion', models.CharField(max_length=40)),
                ('promotion_content', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='website',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='retailer',
        ),
        migrations.RemoveField(
            model_name='shopwebsite',
            name='shop',
        ),
        migrations.AlterField(
            model_name='homepageheader',
            name='isVisible',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Homepage',
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='Shopwebsite',
        ),
    ]
