# Generated by Django 2.1.1 on 2018-11-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storey', '0003_auto_20181104_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVisible', models.BooleanField()),
                ('link_1', models.CharField(max_length=40)),
                ('link_1_content', models.CharField(max_length=40)),
                ('link_2', models.CharField(max_length=40)),
                ('link_2_content', models.CharField(max_length=40)),
                ('promotion', models.CharField(max_length=40)),
                ('promotion_content', models.CharField(max_length=40)),
            ],
        ),
    ]
